import { recipeKey } from "../recipeKey";

// Hand-written recipes for the offline fallback engine.
// Anything not listed here is generated procedurally (see generateFallback.ts),
// so the fallback is still unbounded — this table just makes common paths feel right.
const RAW = `
Earth + Water = Mud
Fire + Water = Steam
Earth + Fire = Lava
Air + Water = Cloud
Air + Earth = Dust
Air + Fire = Energy
Water + Water = Lake
Earth + Earth = Pressure
Fire + Fire = Bonfire
Air + Air = Wind
Lake + Water = Sea
Sea + Water = Ocean
Sea + Sea = Ocean
Earth + Pressure = Stone
Lava + Earth = Volcano
Lava + Water = Stone
Lava + Air = Stone
Volcano + Water = Island
Cloud + Water = Rain
Cloud + Cloud = Storm
Storm + Energy = Lightning
Cloud + Energy = Lightning
Rain + Earth = Plant
Mud + Plant = Swamp
Mud + Water = Swamp
Earth + Plant = Tree
Plant + Water = Sprout
Seed + Water = Plant
Seed + Earth = Plant
Sprout + Earth = Plant
Plant + Plant = Garden
Tree + Tree = Forest
Forest + Forest = Jungle
Tree + Plant = Seed
Tree + Fire = Charcoal
Tree + Tool = Wood
Wood + Fire = Campfire
Campfire + Wood = Bonfire
Fire + Plant = Smoke
Smoke + Smoke = Cloud
Fire + Smoke = Ash
Ash + Water = Mud
Stone + Stone = Wall
Stone + Fire = Metal
Stone + Air = Sand
Sand + Fire = Glass
Mud + Fire = Brick
Mud + Sun = Brick
Clay + Fire = Brick
Earth + Sand = Clay
Brick + Brick = Wall
Wall + Wall = House
Wall + Human = House
House + House = Village
Village + Village = City
City + City = Skyscraper
Wall + Stone = Castle
Castle + King = Castle
Swamp + Energy = Life
Life + Earth = Animal
Life + Water = Fish
Life + Air = Bird
Life + Stone = Human
Life + Mud = Human
Life + Clay = Human
Human + Human = Family
Human + Plant = Farmer
Human + Field = Farmer
Human + Magic = Wizard
Human + Energy = Wizard
Human + Metal = Knight
Human + Castle = King
Human + Space = Astronaut
Human + Rocket = Astronaut
Human + Fire = Chef
Human + Rain = Firefighter
Human + Food = Chef
Human + Robot = Cyborg
Human + Electricity = Scientist
Human + Moon = Werewolf
Human + Fish = Mermaid
Human + Night = Ninja
Human + Treasure = Pirate
Human + Boat = Pirate
Human + Life = Baby
Human + Dead = Zombie
Human + Ghost = Zombie
Human + Bat = Vampire
Human + Animal = Dog
Human + Wolf = Dog
Animal + Animal = Cat
Animal + Earth = Dinosaur
Animal + Time = Dinosaur
Animal + Water = Fish
Animal + Air = Bird
Animal + Plant = Cow
Animal + Field = Sheep
Animal + Desert = Camel
Animal + Sea = Whale
Animal + Ocean = Shark
Animal + Ice = Penguin
Animal + Snow = Penguin
Animal + Night = Owl
Animal + Fire = Dragon
Bird + Fire = Phoenix
Bird + Night = Owl
Bird + Egg = Chicken
Bird + Bird = Egg
Chicken + Chicken = Egg
Egg + Life = Bird
Egg + Earth = Lizard
Lizard + Fire = Dragon
Lizard + Time = Dinosaur
Lizard + Water = Frog
Fish + Fish = Shark
Fish + Sea = Whale
Fish + Electricity = Electric Eel
Fish + Rice = Sushi
Horse + Magic = Unicorn
Animal + Hay = Horse
Horse + Wizard = Unicorn
Dragon + Human = Knight
Dog + Robot = Robot Dog
Dog + Metal = Robot Dog
Dog + Bread = Hot Dog
Dog + Fire = Hot Dog
Cat + Human = Family
Bee + Flower = Honey
Bird + Flower = Butterfly
Flower + Air = Butterfly
Plant + Sun = Flower
Plant + Air = Flower
Plant + Night = Mushroom
Plant + Sand = Cactus
Plant + Desert = Cactus
Plant + Field = Wheat
Earth + Field = Farm
Farmer + Earth = Field
Farmer + House = Farm
Wheat + Fire = Bread
Bread + Bread = Sandwich
Bread + Cheese = Pizza
Cow + Human = Milk
Milk + Time = Cheese
Moon + Cheese = Cheese Moon
King + Banana = Banana King
Computer + Wizard = Technomancer
Tree + Sun = Apple Tree
Tree + Fruit = Apple Tree
Apple Tree + Time = Apple
Apple Tree + Air = Apple
Apple Tree + Wind = Apple
Tree + Banana = Palm Tree
Tree + Beach = Palm Tree
Tree + Sand = Palm Tree
Monkey + Tree = Banana
Animal + Tree = Monkey
Animal + Jungle = Monkey
Animal + Forest = Bear
Fire + Sky = Sun
Fire + Space = Sun
Sky + Stone = Moon
Air + Sky = Cloud
Cloud + Air = Sky
Sky + Sky = Space
Sky + Night = Moon
Space + Stone = Planet
Space + Earth = Planet
Planet + Fire = Sun
Planet + Lava = Mars
Planet + Rust = Mars
Planet + Planet = Galaxy
Space + Star = Galaxy
Sun + Sun = Star
Star + Star = Galaxy
Galaxy + Pressure = Black Hole
Star + Pressure = Black Hole
Space + Ice = Comet
Planet + Stone = Meteor
Meteor + Ice = Comet
Sun + Rain = Rainbow
Sun + Moon = Day
Moon + Moon = Night
Sky + Moon = Night
Day + Day = Time
Night + Day = Time
Sand + Time = Time
Water + Cold = Ice
Water + Wind = Ice
Bird + Ghost = Bat
Fire + Honey = Candle
Water + Mushroom = Soup
Water + Ice = Ice
Ice + Ice = Glacier
Ice + Mountain = Glacier
Rain + Cold = Snow
Rain + Ice = Snow
Cloud + Ice = Snow
Snow + Snow = Blizzard
Snow + Human = Snowman
Snow + Storm = Snowstorm
Snow + Wind = Snowstorm
Storm + Wind = Tornado
Wind + Wind = Tornado
Storm + Sea = Hurricane
Storm + Ocean = Hurricane
Sand + Wind = Sandstorm
Sand + Storm = Sandstorm
Lightning + Lightning = Thunder
Lightning + Metal = Electricity
Energy + Metal = Electricity
Electricity + Metal = Robot
Electricity + Glass = Lamp
Electricity + Computer = Internet
Computer + Computer = Internet
Metal + Glass = Computer
Electricity + Stone = Computer
Robot + Human = Cyborg
Water + Mist = Fog
Cloud + Earth = Fog
Cloud + Mountain = Fog
Stone + Earth = Mountain
Mountain + Mountain = Mountain
Earth + Mountain = Hill
Earth + Hill = Mountain
Mountain + Snow = Glacier
Mountain + Fire = Volcano
Mountain + Lava = Volcano
Sand + Sand = Desert
Sand + Sun = Desert
Sand + Water = Beach
Sand + Sea = Beach
Desert + Water = Oasis
Island + Island = Island
Sea + Earth = Island
Water + Mountain = River
Water + Hill = River
Water + Stone = Puddle
Water + Plant = Sprout
Lake + Plant = Pond
Pond + Fish = Lake
Steam + Earth = Geyser
Steam + Metal = Steam Engine
Steam + Engine = Steam Engine
Metal + Fire = Iron
Metal + Sun = Gold
Stone + Pressure = Diamond
Metal + Stone = Tool
Metal + Wood = Tool
Stone + Wood = Tool
Tool + Stone = Wheel
Wood + Wood = Wheel
Wheel + Wheel = Bicycle
Wheel + Metal = Car
Wheel + Engine = Car
Car + Car = Bus
Car + Farm = Tractor
Car + Field = Tractor
Car + Rail = Train
Steam Engine + Wheel = Train
Steam Engine + Track = Train
Metal + Road = Track
Iron + Road = Track
Iron + Wood = Track
Train + Train = Rail Car
Stone + Sand = Road
Stone + Car = Road
Wood + Water = Boat
Boat + Boat = Ship
Boat + Metal = Ship
Car + Bird = Airplane
Car + Air = Airplane
Metal + Bird = Airplane
Airplane + Space = Rocket
Airplane + Fire = Rocket
Rocket + Space = Spaceship
Rocket + Rocket = Spaceship
Spaceship + Alien = UFO
Life + Space = Alien
Human + Mars = Alien
Space + Metal = Satellite
Engine + Metal = Robot
Energy + Wheel = Engine
Fire + Glass = Lantern
Fire + Tool = Torch
Fire + Paper = Ash
Fire + Wax = Candle
Tree + Paper = Book
Wood + Pressure = Paper
Book + Wizard = Magic
Energy + Life = Magic
Energy + Star = Magic
Magic + Water = Potion
Magic + Stone = Crystal
Magic + Glass = Crystal
Gold + Gold = Treasure
Diamond + Gold = Treasure
Energy + Stone = Explosion
Fire + Explosion = Bomb
Explosion + Sky = Fireworks
Explosion + Night = Fireworks
Life + Life = Love
Human + Love = Family
Air + Love = Music
Bird + Music = Music
Life + Night = Ghost
Ghost + Human = Zombie
Stone + Human = Statue
Water + Statue = Fountain
House + Stone = Tower
Tower + Light = Lighthouse
Lamp + Tower = Lighthouse
Fire + Tower = Lighthouse
Tower + Sea = Lighthouse
Wind + Tower = Windmill
Wind + House = Windmill
Air + House = Windmill
House + Robot = Factory
House + Metal = Factory
House + Engine = Factory
Pyramid + Pyramid = Pyramid
Stone + Desert = Pyramid
Sand + Wall = Pyramid
Wall + Sea = Harbor
Ship + House = Harbor
Bridge + Bridge = Bridge
Wood + River = Bridge
Road + River = Bridge
Wood + Wall = Fence
Wood + Air = Flag
Wood + Human = Tent
Wall + Plant = Tent
Fish + Rock = Coral
Plant + Sea = Coral
Sea + Stone = Pearl
Sea + Fire = Salt
Ocean + Sun = Salt
Bird + Wood = Nest
Bird + Tree = Nest
Plant + Time = Tree
Grass + Sun = Hay
Sprout + Sun = Grass
Hay + Fire = Smoke
Spider + Spider = Web
Animal + Web = Spider
Ant + Ant = Spider
Animal + Sand = Ant
Animal + Mouse = Cat
Lion + Lion = Lion
Cat + Sun = Lion
Cat + Desert = Lion
Animal + Savanna = Lion
Animal + Mud = Turtle
Turtle + Water = Turtle
Animal + Swamp = Frog
Frog + Frog = Snake
Lizard + Lizard = Snake
Animal + Stone = Turtle
Crab + Crab = Octopus
Fish + Magic = Octopus
Animal + Mountain = Elephant
Animal + Big = Elephant
Elephant + Fire = Dragon
Swamp + Monster = Swamp Monster
Swamp + Dinosaur = Swamp Monster
Swamp + Human = Swamp Monster
Coffee + Human = Scientist
Water + Bean = Coffee
Fire + Seed = Coffee
Soup + Soup = Soup
Water + Food = Soup
Cake + Cake = Cake
Bread + Honey = Cake
Bread + Egg = Cake
Milk + Egg = Cake
Bread + Fish = Sandwich
Salt + Peanut = Peanut Butter
Seed + Pressure = Peanut Butter
Fish + Salt = Sushi
Scientist + Human = Doctor
Human + Medicine = Doctor
Human + Potion = Doctor
Bee + Bee = Honey
Flower + Animal = Bee
Plant + Bird = Bee
`;

export const RECIPES: Map<string, string> = new Map();

for (const line of RAW.split("\n")) {
  const t = line.trim();
  if (!t) continue;
  const [lhs, rhs] = t.split("=").map((s) => s.trim());
  const parts = lhs.split("+").map((s) => s.trim());
  if (parts.length !== 2 || !rhs) continue;
  RECIPES.set(recipeKey(parts[0], parts[1]), rhs);
}
